### ISSUE TITLE
Cannot find module 'webpack-cli'

### ISSUE THREAD

**Issue by sinevitch** [webpack/webpack-cli#1560]
I run the command
webpack --mode development --watch
then a get error

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no):

I choose yes and then a get error

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at runCommand.then (/Users/ivansinevich/Desktop/arp-frontend/node_modules/@storybook/core/node_modules/webpack/bin/webpack.js:143:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }

Here is my package.json
"dependencies": {
    "@babel/runtime": "^7.9.6",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",
    "webpack": "^4.43.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/plugin-transform-runtime": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-react": "^7.9.4",
    "babel-loader": "^8.1.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "css-loader": "^3.5.3",
    "file-loader": "^6.0.0",
    "style-loader": "^1.2.1",
    "webpack-cli": "^3.3.11"
  },

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please check you don't have `webpack-cli` globally

**Comment by tandrewnichols** [comment]
I'm experiencing this issue as well, and I think I figured out the issue. I don't know whether this _should_ work or not, but for me, when I type `webpack --json` I get the prompt to install webpack-cli, but then it still can't find the installation (see error message in @sinevitch's original report). That's because `webpack --json` is using the globally installed webpack and the prompt is installing locally. It _seems_ like 1) if there's a _local_ version of webpack, maybe the global one could pass control to it (grunt does this). Or if that isn't something you want to manage and you want to leave it to the user, then 2) when using a global webpack installation, the webpack-cli installation should _also_ be global. Or if _that_ is for some reason not feasible, at the very least 3) it should warn you that you're using a global installation.

**Comment by evilebottnawi** [comment]
@tandrewnichols Can you open an issue in webpack-cli, we can improve it

**Comment by tandrewnichols** [comment]
Would you call this a bug or a feature request? I can see a case for either.

**Comment by evilebottnawi** [comment]
@tandrewnichols Feature, when global and local installations exist we should say what we use local instead global, to avoid confusing

**Comment by tandrewnichols** [comment]
@evilebottnawi See #1653
