### ISSUE TITLE
Remove local fork of yeoman

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#161]
Need an update from @pksjce on the bug she was complaining about recast. Moving to yeoman generators, so this needs to be resolved.

For the yeoman fork, this is removed and replaced in #148

**Comment by thescientist13** [comment]
it appears this would address / resolve https://github.com/webpack/webpack-cli/issues/132

**Comment by ev1stensberg** [comment]
Probably, but not entierly sure

**Comment by ev1stensberg** [comment]
This is underway at #207 , yeoman might be trickier

**Comment by mischkl** [comment]
The git dependency is causing our build to act up due to our proxy on some systems. :frowning_face: One more reason it would be great to get rid of the local fork dependency of yeoman as soon as possible! :wink:

**Comment by ev1stensberg** [comment]
Haha yeah working on it, but need to come up with a good workaround. There's a possibility we'll need to create a temporary `.yo` config file for each scaffold, which shouldn't be be necessary ..

**Comment by kim-10e** [comment]
We just ran into this issue too:

```
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/ev1stensberg/generator/tar.gz/9e24fa31c85302ca1145ae34fc68b4f133251ca0: Request failed \"400 Bad Request\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kimburgaard/dev/10e/release/build/enterprise-client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The workaround to get around this was to manually delete the yeoman-generator entry in our `yarn.lock` file and run yarn again.

Dependencies like these outside of the npm/yarn registries make me super uneasy for a couple of reasons. For one, npm learned the hard way to never allow publicly published packages to be deleted because it breaks dependents, and it requires more oversight to understand where all the 3rd party code comes from.

**Comment by andrewpmontgomery** [comment]
#313

**Comment by ematipico** [comment]
We can't at the moment because it exposes the `cli` to some vulnerabilities

**Comment by bponomarenko** [comment]
I have special setup where I don't have git installed in the same environment, where I have npm. Not having git prevents me from installing webpack-cli at all.

**Comment by dhruvdutt** [comment]
@ematipico Which vulnerabilities?
I think we were having facing issues like #291 when using the published fork so we reverted to using the fork in #291 which introduces proxy bugs.

**Comment by mihir478** [comment]
I'm getting the following. I believe this is due to a corporate firewall issue but could also be a proxy issue. Anyone else run into this?

λ  yarn add webpack-cli -D
yarn add v1.5.1
[1/4] Resolving packages...
warning webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
error An unexpected error occurred: "https://raw.githubusercontent.com/ev1stensberg/generator/9e24fa31c85302ca1145ae34fc68b4f133251ca0/package.json: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in

**Comment by dhruvdutt** [comment]
@mihir478 We've identified this error and the fix should out soon. You can track it at #323.
Thanks for reporting.

**Comment by ev1stensberg** [comment]
`webpack-cli@2.0.11`
