### ISSUE TITLE
webpack-cli info being run when not desired

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-cli#1648]
**Describe the bug**

I was trying to run `webpack-cli serve` with the logging flag set to `info` like this: `webpack-cli serve --client-logging info`. It seems that the `info` string was identified, and instead of running `webpack-cli serve` it just outputted system information like it would with `webpack-cli info`. Since `info` is a valid option for logging, we need to do more than just check that there is an `info` string in the argv.

**To Reproduce**

Put `info` as an option for something in a way that is valid, and the CLI will end up running `webpack-cli info`.

**Expected behavior**

`webpack-cli info` should not be run in certain cases

**Comment by jamesgeorge007** [comment]
This seems to be happening because `info` comes before `serve` in `cli-flag` definition.
`webpack serve --client-log-level info`
The present way of parsing commands picks `info` over `serve`. 
https://github.com/webpack/webpack-cli/blob/d087c61a8a64359a8f520b4c3916948cb846a55c/packages/webpack-cli/lib/bootstrap.js#L18

**Comment by evilebottnawi** [comment]
We should rewrite it, using `process.argv.includes` is not safe
