### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#199]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
This package is installed using npm
**If the current behavior is a bug, please provide the steps to reproduce.**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Since now this is a dependency of webpack/webpack, we should probably also move this over to yarn as well. Initial testing shows trying to link webpack/webpack locally wasn't working to friendly with webpack-cli.

webpack-cli@latest

**Comment by billyjanitsch** [comment]
@TheLarkInn @ev1stensberg @sokra sorry if this has been discussed elsewhere (I searched and didn't find anything), but why was `webpack-cli` added as a dependency to `webpack`?

The standard for separate CLI packages seems to be the other way around: the CLI depends on the node API. For example, `babel-cli` depends on `babel-core` (but not vice-versa), `postcss-cli` depends on `postcss`, etc.

If it's simply because you want installing the `webpack` package to give you the CLI, then why not move the CLI to the `webpack` npm namespace and move the rest to something like `webpack-core` for v4?

It seems odd for `webpack` to depend on `webpack-cli` _and_ `webpack-cli` to depend on `webpack`, especially because it causes linking/versioning issues like this.

**Comment by ev1stensberg** [comment]
#202  #203 , @billyjanitsch yep, you're right 👍

**Comment by billyjanitsch** [comment]
@ev1stensberg I don't think #202 is quite right.

I'm suggesting that `webpack-cli` _should_ depend on `webpack`, but `webpack` should _not_ depend on `webpack-cli`. This is how other separate CLI packages work, e.g. Babel and postcss. If you think about the dependency hierarchy logically, this makes sense: the CLI requires (a specific version range of) the node API to function, but not vice versa.

If you want `npm install webpack` to give you the CLI, then one option is for the node API (what is now `webpack`) to be published as `webpack-core` and the CLI as `webpack`.

**Comment by ev1stensberg** [comment]
@billyjanitsch We're gonna make the CLI a peerdep in webpack before releasing
