### ISSUE TITLE
Cannot run --help

### ISSUE THREAD

**Issue by codymikol** [webpack/webpack-cli#2278]
**Describe the bug**

I am unable to run the command `webpack --help`

**What is the current behavior?**

When I run the command I get the following error

```
$ webpack --help
[webpack-cli] Unknown command 'init'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

**To Reproduce**

I am just running `webpack --help`

**Expected behavior**

I will see the help menu

**Screenshots**

![image](https://user-images.githubusercontent.com/13606342/103375490-5e2e8400-4aa8-11eb-8972-afaf3bd40c07.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.47 GB / 32.00 GB
  Binaries:
    Node: 15.3.0 - /var/folders/3v/lvflb0gs6z5bhzkjqq_1936r0000gn/T/yarn--1609355079374-0.40846623746145627/node
    Yarn: 1.22.10 - /var/folders/3v/lvflb0gs6z5bhzkjqq_1936r0000gn/T/yarn--1609355079374-0.40846623746145627/yarn
    npm: 7.0.14 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 79.1.1.23
    Chrome: 87.0.4280.88
    Edge: 87.0.664.66
    Firefox: 79.0
    Safari: 14.0.2
  Packages:
    copy-webpack-plugin: 7.0.0 => 7.0.0 
    extract-text-webpack-plugin: v4.0.0-beta.0 => 4.0.0-beta.0 
    html-webpack-plugin: ^4.5.0 => 4.5.0 
    karma-webpack: ^4.0.2 => 4.0.2 
    uglifyjs-webpack-plugin: ^2.2.0 => 2.2.0 
    webpack: ^5.11.1 => 5.11.1 
    webpack-cli: ^4.3.0 => 4.3.0 
    webpack-dev-server: ^3.11.1 => 3.11.1 
    webpack-merge: ^5.7.3 => 5.7.3 

**Additional context**

N/A

**Comment by codymikol** [comment]
I can confirm this is not an issue in the previous version 4.2.0, only in 4.3.0

**Comment by codymikol** [comment]
going to bisect and see if I can find the problem commit

**Comment by codymikol** [comment]
When I build / run 4.3.0 locally it works fine, but when I pull from npm, I get the above error, does anyone else experience this as well?

**Comment by solmstead25** [comment]
@codymikol

It is related to how the commands are being parsed before the options.

Running the sub-command (`externalBuiltInCommandsInfo` in the source) first results in the expected behavior. ie. `webpack b --help`

There is a default help option, but it isn't behaving as expected, I am assuming. 

The change in the behavior of how options are being parsed resulted in behavior that I did not expect, and is the issue that I originally checked here for.

Previously you could run, `webpack-cli --mode development s`. Now that results in an error message leading to this default help prompt, which doesn't work as a command / option either.

However, running `webpack-cli s --mode development` works as you would expect.

**Comment by snitin315** [comment]
I will look into it.

**Comment by benpaodewoniu** [comment]
I have same problem!

**Comment by alexander-akait** [comment]
Fixed in master

**Comment by alexander-akait** [comment]
Release will be today
