### ISSUE TITLE
Seperate options object logic from argv && Transformation Parser

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#25]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

[Process-Options](https://github.com/webpack/webpack-cli/blob/master/bin/process-options.js) is currently making sure webpack gets options applied to the compiler. We're doing some checks here and there before and after the init of the compiler.

We should split or refactor the logic from the `options` object so that our argv object doesn't serve as a "cleanup" of some flags/options from the CLI. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Nein

**What is the expected behavior?**

N/A

**If this is a feature request, what is motivation or use case for changing the behavior?**

This allows us to have a clear project structure, perhaps some perf gains and  a moreso maintainable CLI. Doing these changes allows us to find common ground from `options` and `argv` instead of treating the argv option partially after we've gotten `options` built up.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Snapple OSX

**Comment by ev1stensberg** [comment]
- https://github.com/webpack/webpack-cli/blob/master/bin/process-options.js#L147
- https://github.com/webpack/webpack-cli/blob/master/bin/process-options.js#L178
- https://github.com/webpack/webpack-cli/blob/master/bin/process-options.js#L138

**Comment by ev1stensberg** [comment]
1. Remove inquirer types  as we don't need several, we only use one.

**Comment by pksjce** [comment]
We might use list or checkbox types also right?

**Comment by ev1stensberg** [comment]
We'll see how the parser and transformation package turns out. We should export inquirer and all needed resources as a utility suite to develop an addon. Reserved this from npm: https://www.npmjs.com/package/webpack-addon

**Comment by ev1stensberg** [comment]
![technical scheme](https://cloud.githubusercontent.com/assets/16735925/21578242/f92db75a-cf78-11e6-8b78-f97bb9964ca8.png)

**Comment by ev1stensberg** [comment]
@kenwheeler @DanielaValero @pksjce  Seems approachable?

**Comment by DanielaValero** [comment]
Hi @ev1stensberg it looks like the diagram is referring to the `init` and that this issue is about the refactoring and migration of the options we pass to the compiler via the cli, which are currently available in `webpack`. 

I'd think about the structure of `webpack-cli`, more like in two big areas:

1. `init` && `migrate`: which are consuming the validation and transformations of code
2. `<options>`: which are sending options to the compiler, to tell it to perform specific tasks.


I will prepare later today a graph to share somewhere here, to illustrate this, and will try to add some more details. Later on, we can all feed it, and detail it wherever is required, in order to have a clear idea of where what belongs. 

Does it make sense?

**Comment by carlos-** [comment]
@DanielaValero, it makes total sense to me. I like the idea of organizing the architecture that way. did you finish the graph?

**Comment by DanielaValero** [comment]
Hello @carlos- 

I've just added an asciidoc diagram in the features wiki page: https://github.com/webpack/webpack-cli/wiki/Features-definition---v1

The same structure, would be at a point expressed in the folder structure, which we are defining in #52

**Comment by ev1stensberg** [comment]
Closing this for now, going to do a write up on a Higher Order ticket.
