### ISSUE TITLE
Improve Unknown options support

### ISSUE THREAD

**Issue by Paitum** [webpack/webpack-cli#2737]
**Is your feature request related to a problem? Please describe.**

We require webpack to build artifacts with a fine level of build control for various purposes. To achieve this we created a set of webpack.config.js files that use Node & CommonJS to imperatively construct the appropriate config(s). They rely on `process.argv.includes('--optionName')` to pick up options.

We are looking to make the contract easy, for example; to build only the ES5 version of the DEMO target in development mode using watchers, I would expect:

```
yarn build --es5 --app=demo --development --watch
```

Unfortunately the webpack-cli fails with `Unknown option: "--es5"`.

**Describe the solution you'd like**
A non-prescriptive solution that allows us to tailor our webpack.config.js infrastructure to meet our business needs. Webpack runs in NodeJS, as do our webpack.config.js scripts-- so allowing us to parse the command line arguments for our needs would make the "flags" easy to use.

I would very much like to be provided with a flag that disables the error, like `--allow-opts`. That way I can add that to my package.json script, like `"build": "webpack --config ./build/webpack.build.config.js --allow-opts"`.

**Describe alternatives you've considered**

I considered using the `--env` approach, but that requires refactoring our configuration files to return functions that accept `(env, args)`. We can no longer centralize our shared state, e.g. `const { isES5 } = require('./common');', but instead must pass the `env` and `args` downstream. It overly complicates all our infrastructure to be function-based.

This approach also forces a more cumbersome user experience, for example the previous example would be:

```
yarn build --env=es5 --env=app=demo --mode=development --watch
```

A second approach is to use cross-env and create lots of environment vars. I'm not sure how that would work without creating a lot of package.json scripts for every permutation:

```
yarn build:es5:demo --mode=development --watch
```

Finally, I considered NOT using the webpack CLI and manually running the webpack compiler, but I started getting stuck with issues due to my lack of familiarity with running webpack via its NodeJS API. (I may return to that effort again, but wanted to make a post first.)

**Comment by alexander-akait** [comment]
Sorry, we already discussed about it, only `--env` options are supported, if this does not suit you, then it is better to create own CLI. You can use `--env app.name="demo"`. Even more if we implement unknown custom options it will create problems for new options in future, because if you use `--app` and we implement the `--app` options if will faced with breaking change. Also there are a lot of problem more: bad error messaging, overlapping, unknown how implement parsing for new options and more and more.

**Comment by kaysonwu** [comment]
I also have this need. When my `webpack` configure the export function, I want to pass parameters through cli.

**Comment by kaysonwu** [comment]
@alexander-akait  I don't think the unknown custom options will cause trouble for the new options of `webpack`, because the person who provides the unknown definition options has the obligation to deal with it.

**Comment by anshumanv** [comment]
> I want to pass parameters through cli.

You can use `env` flag to achieve this

**Comment by anshumanv** [comment]
https://webpack.js.org/api/cli/#env

**Comment by hparadiz** [comment]
This shouldn't even be something we need to request. Thanks for breaking my workflow @alexander-akait

Webpack 4 works fine with custom CLI switches.

What's the point of having a config written in JavaScript if you're gonna block basic features of the language.

![image](https://user-images.githubusercontent.com/195216/151094860-b2dbbc78-b91a-4a85-8c7b-765e72dd903e.png)

It's not up to you.

Great now I have to fork webpack-cli in my projects because of bad design.

**Comment by alexander-akait** [comment]
> This shouldn't even be something we need to request. Thanks for breaking my workflow @alexander-akait

I don't support toxic behavior 

> Webpack 4 works fine with custom CLI switches.

webpack v5 too

> What's the point of having a config written in JavaScript if you're gonna block basic features of the language?

We didn't break anything, you have `--env` use them
