### ISSUE TITLE
webpack is not listed as a peer

### ISSUE THREAD

**Issue by waterfoul** [webpack/webpack-cli#295]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
you can install webpack-cli witghout webpack and get no warning

**If the current behavior is a bug, please provide the steps to reproduce.**
npm install webpack-cli on an empty project

**What is the expected behavior?**
An npm peer requirement warning

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

**Comment by dhruvdutt** [comment]
I think fix should be to add webpack to `"peerDependencies"` inside `package.json`. 

@ev1stensberg What minimum version of `webpack` we support?

**Comment by ematipico** [comment]
Version 4

**Comment by dhruvdutt** [comment]
@ematipico I'm not sure about other commands but as per the [docs](https://github.com/webpack/webpack-cli/blob/master/MIGRATE.md) the `migrate` command only supports migrations from version 1 to 2.
Are the docs stale?

**Comment by ematipico** [comment]
Webpack supports migration from 1 to 2 as you stated but the whole cli is officially ported since webpack 4. 

From webpack 1 to 3 there was no need to have the cli installed. The cli was a plus (migration, creation of the config file)

From v4 the entire cli of webpack has been ported inside this repository, hence we needed to have a double relationship between webpack and the cli itself. So the first version that we have to support is 4.

**Comment by dhruvdutt** [comment]
@ematipico Makes sense. I did a PR to add it. #297
