### ISSUE TITLE
Scoping: init feature

### ISSUE THREAD

**Issue by kenwheeler** [webpack/webpack-cli#32]
Lets use this ticket to discuss the scope of the `init` command

TODO: 

- [ ]  Agreed upon high level scope points go here

**Comment by ev1stensberg** [comment]
The init command should initiate two basic questions, input and output(The most general variables that we can make for all common webpack configurations ). You can extend the scaffolding by supplying a second argument`<Array>` to the init command that will make the inquirer add extra questions to the prompt and generate a webpack config accordingly. 

Example: 

`webpack --init webpack-addons-react` - Generates a inquirer prompt with React specific questions and implementation rules passed to our transformer/parser. The parser as I've defined it, should validate incoming inquirer questions and send them to the transformer for transformation. 

We also brought up to extend babel presets, options and such too. I think that is too broad, perhaps the best solution would be to encourage the creator of a webpack-addon to include that in their own respective README´s. 

cc @DanielaValero

**Comment by DanielaValero** [comment]
Hi, 
About the main idea of the init, this is what we have spoken so far:

The init should have as a minimum the next functionality:
- Create a config for different environments (prod, dev, testing)

Other functionalities / nice to haves:
- Generate settings for frameworks

we could design it in a way that allow developers of frameworks, to write plugins, that would help to generate on top of that, specific settings for frameworks. 

About how to do this, we said:

* We could use the plugin system of webpack, however the learning curve of it is quite high.
* We could check how others are doing it, and try to apply similar design options

Next steps:
* Check what the current status of the init is. @ev1stensberg  / @pksjce do you have any input here?
  As for last comment of @ev1stensberg, we have got: 
  - Inquirer in place that outputs a question and receives an answer
  - It's set to get several arguments

* Match what we have to the goal of generating settings for different environments
* Create small tasks of TODOs
* Decide wether we will add the plugin system to allow developers to plug in their `init` for specific frameworks. Decide when we will add it. 

Note: In case we will have the plugin system, but not in the v1, we should anyways make a code design plan for it, and setup the code in a way that is flexible enough to add this functionality later. This would reduce the amount of rework that we might have to do if we do it otherwise

**Comment by ev1stensberg** [comment]
I'll put up a set of things left on the init sometime during this week.

**Comment by ev1stensberg** [comment]
Old, new discussion about the packaging system is on #42 .
