### ISSUE TITLE
Scoping: migrate feature

### ISSUE THREAD

**Issue by kenwheeler** [webpack/webpack-cli#33]
Lets use this ticket to discuss the scope of the `migrate` command

TODO: 

- [ ]  Agreed upon high level scope points go here

**Comment by ev1stensberg** [comment]
`migrate` should transform from `v1` to `v2`, that's it.

**Comment by DanielaValero** [comment]
Hi, I'd say that in order to be able to split this into smaller tasks, would be good to have a more detailed plan of the implementation of this. 

@pksjce: You've been doing some work here, and mentioned in our call that the ground work you've been setting is quite in place and would be ready to get some extra hands in.

Would you share with us here the code design ideas that you've got? Perhaps maybe starting from  a high level point of view, and then we can get more into details?

**Comment by pksjce** [comment]
@okonet - We need to collate all thats done in #40 and #6. After that we can come up with some concrete tasks that can be easily split.
