### ISSUE TITLE
`webpack-cli init`  - Support for webpack version 4

### ISSUE THREAD

**Issue by Legends** [webpack/webpack-cli#350]
**Do you want to request a *feature* or report a *bug*?**

 - Feature
**What is the current behavior?**
Creates an old starter template for webpack.config.js
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
CommonsChunkPlugin is deprecated and would not expect it in the template.
Add a question which version of webpack the user wants to use.

**Comment by EugeneHlushko** [comment]
Not sure it should differentiate version via user input and add an extra level of complexity into the generator, imo just link previous version as you would for installing older webpack in package.json. Whilst i am with you on fixing the writing of webpack4 ready config file including `mode`. If you want i can up a PR @Legends

**Comment by Legends** [comment]
@EugeneHlushko 
I just recently started to get my hands on stuff like node, webpack, different packages I apologize for if I sometimes ask dumb questions :-)...

So when I do `webpack-cli init` how can `webpack-cli` know which version of webpack I will be using?
You mean `npm link` a specific version of webpack in the current project and the `webpack-cli` will know what to generate?

Sure, provide a PR.

**Comment by EugeneHlushko** [comment]
@Legends 
Latest `webpack-cli` should work by default against current version of webpack (4+). If there is a case where you are using older webpack version lets say `3.10`, you could just specify the older `webpack-cli` version in `package.json` which does support that older `webpack`. Starting to add support for older versions via prompts might just get too messy later on if we keep it in one file and continue adding if statements, right now it seems trivial since the difference is not that big, but that might quickly change when `webpack` version 5 lands and as webpack 4 gets progressed.

Version differentiation can also be achieved by making extra files for that init command to maintain them separately if its worth it and people upvote the feature. E.g.

```
if (version < 4) {
 return require('./olderversion.js');
} else {
 return require('./currentversion.js');
}
```

**Comment by EugeneHlushko** [comment]
@ev1stensberg im on it, pls assign

**Comment by Legends** [comment]
I use TypeScript and not `Babel`, but when I create a new configuration I get:

```
                        {
				test: /\.js$/,
				exclude: /node_modules/,
				loader: 'babel-loader',

				options: {
					presets: ['env']
				}
			},
```

**Comment by ematipico** [comment]
@EugeneHlushko issue assigned to you :)

**Comment by ev1stensberg** [comment]
@Legends can't you just use file read at the location `package.json`?

**Comment by Legends** [comment]
@EugeneHlushko  Thanks for the clarification

**Comment by Legends** [comment]
@ev1stensberg Sorry, what do you mean?

**Comment by ev1stensberg** [comment]
nvm
