### ISSUE TITLE
Third-Party Vulnerability: glob-parent package

### ISSUE THREAD

**Issue by nydrelAcuity** [webpack/webpack-cli#3594]
**Issue**
`webpack-cli` has transitive dependencies on versions of [`glob-parent`](https://www.npmjs.com/package/glob-parent) that contain a vulnerability. These dependencies should be updated to use `glob-parent` `6.0.2`

See [CVE-2021-35065](https://nvd.nist.gov/vuln/detail/CVE-2021-35065)
See [`yarn.lock`](https://github.com/webpack/webpack-cli/blob/master/yarn.lock) for webpack-cli

**Additional context**
- I assume this is also relevant to the main [`webpack`](https://github.com/webpack/webpack/blob/main/yarn.lock) project
- Opening a "bug" seemed like the appropriate template for this issue. The security policy for this project is helpful and it'd be nice if there were a template for reporting third-party vulnerabilities.

**Comment by alexander-akait** [comment]
We don't have `glob-parent` in our deps https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/package.json#L36, please check you have used the latest version of webpack-cli, also you can try to reinstall dependecies, because the vulnerability already fixed, sorry we can't fix it here
