### ISSUE TITLE
[Question] Existing Log of Breaking changes for v3 to v4

### ISSUE THREAD

**Issue by nsunga** [webpack/webpack-cli#3674]
Hello maintainers!

I wanted to know if there is a list of breaking changes for those on v3 migrating to v4.

I've digged in the change log and it looks like theres only breaking changes for v5: https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md#breaking-changes

Am I correct with this being up to date?
Also is there an existing migration guide for v3 to v4?

Looks like there was previously a guide for v1 - v2, v2 - v4: https://github.com/webpack/webpack-cli/blob/webpack-cli%404.0.0/MIGRATE.md

**Comment by alexander-akait** [comment]
Unfortunately, we do not have them, the developers who led this version did not do this (at least I don’t where it is)... SO my recommendation just bump to v5 and tests all commands, also please look at docs, they are up to days, I cloed issues, because it is really hard to collect them due mixed merging, missing good titles in commits and etc. Anyway I will answer and help with any problems here and feel free to ping me if you will have problems, sorry for that

**Comment by nsunga** [comment]
thats okay and sounds good to me. thank you! @alexander-akait
