### ISSUE TITLE
Migrate and init should move to mini-css-extract-plugin

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#373]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
At the moment, when migrating or initiating a new configuration `ExtractTextPlugin` it still  uses `ExtractTextPlugin`. `ExtractTextPlugin` should become `MiniCssExtractPlugin`

**What is the expected behavior?**
The `cli` should ask it the user wants to migrate to v3 or v4 of webpack. If v4, it should migrate to `MiniCssExtractPlugin`. The init feature should use `MiniCssExtractPlugin` as well.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Supporting the new `MiniCssExtractPlugin`

**Comment by PlayMa256** [comment]
Do we want to keep v1->v2 migration or deprecate them and have just v3->v4?

**Comment by ematipico** [comment]
Honestly I'd propose a breaking change and going straight from v3 to v4

**Comment by bitpshr** [comment]
I can work on this feature if no one else has started it.

**Comment by ematipico** [comment]
@bitpshr Thanks! You can pick it up! Consider that half of the job is already done here #363 
You'd just need to work on the migrate part

**Comment by PlayMa256** [comment]
@bitpshr yes, we are creating a break change here. V3->V4. Yes again, Change `extract-text` to `mini-css`

**Comment by bitpshr** [comment]
Thanks @ematipico and @PlayMa256. I've completed an [initial upgrade](https://github.com/webpack/webpack-cli/compare/master...bitpshr:feature/v3-v4-extract-migrate?expand=1) of the `ExtractTextPlugin` transformation on my branch. It now transforms v3 configuration to v4 instead of v1 to v2.

Was the intention to use this issue / PR to track all other transformation upgrades as well, or should I submit my PR as is?

**Comment by PlayMa256** [comment]
Just open a pr for this. Since this issue just refeers to `miniCss` lets stick with that. If any other transformations are required, we can open more.

**Comment by ematipico** [comment]
After an internal discussion about the `migrate`, where the intention is to _migrate the configuration always the most up to date version_, so in this case `webpack 4`, I think that a breaking change is not necessary and we should move straight to `MinCssExtractPlugin`. What do you guys think?

**Comment by PlayMa256** [comment]
Well, this is sort of a "breaking change" anyways, since we are removing the option to migrate to older versions. And yes, i started touching onto some files, but bitshr already said he would like to work, so i let him do that. My initial idea was to remove the `extractTextPlugin` folder and have just a `miniCssExtractPlugin` folder and in there all these transformations. In this way it would be much cleaner.

**Comment by bitpshr** [comment]
@ematipico @PlayMa256  I agree that we should always migrate to v4, but do we support migrating from v1 -> v4, v2 -> v4, and v3 -> v4, or just v3 - v4? If we decide to make our transformations be able to upgrade _any_ previous version to the latest version, the AST logic will get incredibly complex.

I vote that we move to actively support upgrading the previous version to the latest version, so v3 -> v4 in this case. When v5 is released, we should upgrade our transforms to instead support upgrading v4 - v5, and so on.

**Comment by PlayMa256** [comment]
I made the same question, when i first read this issue. @ematipico answer was:

> Honestly I'd propose a breaking change and going straight from v3 to v4

You comment resonates with what he said, and i do agree too. Let's just support newest versions of the `webpack` config, otherwise the whole migration folder would be such a mess.

**Comment by bitpshr** [comment]
Sounds good to me. PR submitted for the `ExtractTextPlugin` transform. Issues opened for remaining transforms as well.
