### ISSUE TITLE
Bug: semantic-release script tries to push old tag

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack-cli#428]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
The `semantic-release` npm script seems to push an old tag which could be caused by the loaded Travis cache.

**If the current behavior is a bug, please provide the steps to reproduce.**

Take a look at the CI builds and see that the `semantic-release` script pushed old tags.
https://travis-ci.org/webpack/webpack-cli/jobs/373140151#L4934-L4975

**What is the expected behavior?**
The `semantic-release` script should use the latest version.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

**Comment by ematipico** [comment]
This is due to the actual process that we set up in our CI. We are going to change it in the next few days in order to achieve an agreement and set on stone how the release process will work.

The gist is, we want to release through CI in order to automate the shipping of the code. Although we have to make sure that the PRs don't get merged into master. Probably we will switch to a real git flow: merge PRs against develop and merge into master when we are ready to cut a release. Although we will need to change Travis matrix

**Comment by ev1stensberg** [comment]
We have two scenarios, one is to only use matrices, the other one being build steps. Build steps and matrices doesn't work well together.

**Comment by DanielRuf** [comment]
Hm, what is the better option? I guess build steps.

**Comment by DanielRuf** [comment]
> ev1stensberg (Even Stensberg) closed this an hour ago

Do we still need build steps?

**Comment by ev1stensberg** [comment]
I don't think so, we've set one up now. If you wanna help out, please have a go at https://github.com/webpack/webpack-cli/issues/471. I'll be here if you need help :+1:  Also, that should be submitted to the next branch, not master

**Comment by DanielRuf** [comment]
Understood, thanks so far.

**Comment by ev1stensberg** [comment]
Started some work on this at #475 .
