### ISSUE TITLE
[UI] Detect configurations or select them

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#648]
Given the possibility to bootstrap the UI project internally, the server should be able to detect the webpack configurations. Ideally file names like `webpack.*`

Alternatively, the user can choose a file from the filesystem. 

Anything else I'm missing for the sake of the feature?

**Comment by LakshSingla** [comment]
I think it would be better if the user is able to choose the config file from the filesystem. If not possible, we can detect all the files starting with `webpack\.*` and provide the user with the option of which configuration to use.

**Comment by anshumanv** [comment]
The way this works is in vue ui they provide an option to import a project where you need to traverse directories and it detects which project uses webpack so you can just go ahead and import it and then it will be added to the projects tab.

I'll write quick util to check for webpack projects since we already have a regex to detect it so it will be fairly easy to implement. Sending a PR soon. 👍
