### ISSUE TITLE
Needs investigation: IE 11 not support

### ISSUE THREAD

**Issue by houzhitaohzt** [webpack/webpack-cli#761]
**Describe the bug**
![image](https://user-images.githubusercontent.com/20673060/52847727-ef601000-3147-11e9-8b7f-d98bff60b35d.png)

![image](https://user-images.githubusercontent.com/20673060/52847736-f6871e00-3147-11e9-9db5-233f9fd05f9d.png)

![image](https://user-images.githubusercontent.com/20673060/52847769-0c94de80-3148-11e9-8e84-1621b0b56f7e.png)

ansi-regex is not compile use babel

'use strict';

module.exports = () => {
	const pattern = [
		'[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[a-zA-Z\\d]*)*)?\\u0007)',
		'(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PRZcf-ntqry=><~]))'
	].join('|');

	return new RegExp(pattern, 'g');
};

**Comment by misterdev** [comment]
Hi @houzhitaohzt, could you share your webpack configuration and an english translation of the error? :)

**Comment by evenstensberg** [comment]
Could you make a repository with a reproduction of the issue?

**Comment by houzhitaohzt** [comment]
> Could you make a repository with a reproduction of the issue?

Project sample address:  https://github.com/houzhitaohzt/2019-react

**Comment by misterdev** [comment]
Hi @houzhitaohzt sorry for the late reply, I've set up a Windows pc to try this but testing your repo I can't see any problem.

1. Are you sure that your repository (2019-react) has the problem you are describing? I can't see any regex in your code.
2. Could you add a guide to reproduce the error to your README.md? Possibly in English thanks 😇

If the problem is solved please consider closing this issue :)
