### ISSUE TITLE
GSoC19

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#790]
**Hello Webpack,**
My name is Pranshu Chittora a sophomore CS student from India. As @webpack is a participating organisation in GSoC 2019, the ideas proposed are quite interesting but the details provided are not sufficient enough to write a good proposal. 
                            
I am interested to work on `CLI- Infrastructure & Documentation`. Kindly provide some more details about it.

Thank You :+1: 

CC @evenstensberg @dhruvdutt

**Comment by evenstensberg** [comment]
Hi @pranshuchittora . You can have a look at https://google.github.io/gsocguides/student/finding-the-right-project#shortlist

You can come up with your own ideas. The ideas are briefly mentioned, because the proposal is your outline of this problem space, we are not writing the proposal for you. That being said, I'm happy to help you out to write up a proposal if you contact me through email. Issues are used for actual issues, not mailing lists.

As a student you should try to make contributions to the project or organization so you are better prepared and have knowledge of what we are talking about in the ideas lists. 

Send me an email and I'll get to you once I'm available ❤️
