### ISSUE TITLE
[NEXT]: Re-visualizing the new CLI Interface

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#819]
# Problem

The old(current) CLI visually is outdated and doesn't make too much sense for people to have an overview of what is going on with their compilations or builds. I think that primarily is because webpack has evolved during the years and the usage has changed since initially made. For instance, initially webpack may have been intended to be only bundling a few files, thereby not emitting such a big log.

This is what a webpack build currently looks like (with my slightly tweaked bash):

![Skjermbilde 2019-04-08 kl  20 00 06](https://user-images.githubusercontent.com/16735925/55746001-ec431b00-5a38-11e9-80f2-5908aed290e4.png)

# Rotation/change needed 

A new visual interface for webpack-cli is needed. Current work is done at the [`next`](https://github.com/webpack/webpack-cli/tree/next) branch of webpack-cli, which lays the foundation for our new breaking change.

Currently the new visual output looks like this:
![Skjermbilde 2019-04-08 kl  20 04 45](https://user-images.githubusercontent.com/16735925/55746285-9e7ae280-5a39-11e9-935f-5327a7d39e21.png)

This doesn't look that good and there is definitely room for improvement, and improvement needs to happen. Now, there are several things that should be improved but before that, what is the scope a compilation? What is interesting to a developer? These things needs to be taken into consideration before we implement it. 

# Discussion

- What is interesting to a developer?
- Is metadata interesting (date, hash, version, etc) or are developers using a format for `json` output? (This should be implemented as a reporter feature instead)
-  Will a `entry - size - outputted` format work?
- The new visuals would need to be simple, clean and easy to understand
- Should the interface be easy to stringify and pipe for people to use further down them stacks ( devops)?
- Should we have a logger on top of the compilation table, do we need a compilation table to show info? What are the alternatives?

# Further info

- What should watch look like? Should we use the new reporter feature for that?
- Should [`webpack-log`](https://github.com/webpack-contrib/webpack-log) be used for reporting?

**Feedback from developers using webpack about the compilation and their use cases and/or suggestions would be great**

**Comment by misterdev** [comment]
`<IMO>`

**What is interesting to a developer?**
Generally showing the most relevant information at the bottom so that people don't need to scroll the terminal to understand what is happening, I'm thinking about:
- Success: I expect to see my compilation table, a lot of green and sometimes a simple tip telling me how to improve something (eg. "set the mode option" or "your bundle is large, split it in chunks" or "update webpack")
- Error: errors should be easy to identify and understand, I really like the look of
 [friendly-errors-webpack-plugin](https://github.com/geowarin/friendly-errors-webpack-plugin): 
  <img width="394" alt="Screenshot 2019-04-11 at 13 21 14" src="https://user-images.githubusercontent.com/11232797/55953577-bed6b700-5c5c-11e9-862e-9463ec9fb933.png">
  <img width="394" alt="Screenshot 2019-04-11 at 13 21 21" src="https://user-images.githubusercontent.com/11232797/55953585-c302d480-5c5c-11e9-82ef-56989531715b.png">
- Using webpack-dev-server: the messages "Project is running at http://localhost:8080/" is one on the most relevant information when I run the command the first time and it should be at the bottom:
  <img width="1328" alt="Screenshot 2019-04-11 at 13 27 33" src="https://user-images.githubusercontent.com/11232797/55953995-cf3b6180-5c5d-11e9-8306-2cecba8658d5.png">

Talking about other information that we are currently showing:
- The `entry - size - outputted` looks good to me
- I think `date` is particularly useful when in whatch mode
- I've never had the need to look at `hash` & `version`

**Should the interface be easy to stringify and pipe for people to use further down them stacks ( devops)?**
I've seen that the most popular libraries created to override webpack's output (webpack-stylish & friendly-errors-webpack-plugin) have a "parse&format" structure. I'm not sure I'm getting what you mean, but I think that having a reporter API emitting well structured/parsed logs would make easy to handle the output. Also providing reporters utilities like `stats.toJson`, `stats.toString`, `stats.toTable` and something to style the output would be enough to cover every use case :)

**Should webpack-log be used for reporting?**
I like webpack-log but it can't be customized and I don't think we need a logger name before every cli log. Also, AFAIK it doesn't provide a method to print that doesn't prepends something to the output, so if we want to print a table we have to either use `console.log`, or use `webpackLog.log(table)` adding a "\n" before the table so that it doesn't broke the first line.

*For me, the best ways to improve the output are:*
- formatting properly, sometimes it feels like a wall of text, solving this would improve *a lot* the UX
- having better error messages and formatting

`</IMO>`

**Comment by k-five** [comment]
I pointed out some problem I saw with the CLI here #820  
In terms of `--option` design for Terminal usage webpack is poor comparing to the most Unix-Linux CLIs.  
But I want to talk about color and table  (=ANSI Escape Sequence) which is my [specialty](https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux/28938235#28938235)

As a full-time command-line user I usually run several tools and redirect the output (stdout, stderr) or all to a Global FIFO (A Linux Special Device).
I noticed that almost all tools I am using lose their color, except mine which is a simple CLI for blogging.
You can fix yours by using `hex` value for the output which is an easy fix.
Here is the output of `webpack` and my utility (It is a node.js tool)

![2019-06-26-webpack-to-fifo](https://user-images.githubusercontent.com/18571844/60164762-6488d380-9813-11e9-9ae4-714a05bd80f5.png)


Let talk about a neat and clean output which I did it and doing it all time because UI / UX is important to me. For having a clean and nice output drawing a **Table** is preferable but you should be careful because we are not going the have a **fixed** row or column for our table.
The table I am seeing:

> Currently the new visual output looks like this:


Will be a headache in the future if you want to add another column to it. An example of it is my project for reporting bugs of Top Iranian Website using `curl` and Terminal

```
curl -sL bugfa.ir/list
```
It is clean. Is not it?

![20190626_131311](https://user-images.githubusercontent.com/18571844/60165395-71f28d80-9814-11e9-93ed-d08204219fcd.png)

Although it is clean and neat yet I prefer my other Table Design with  a little bit different so it lets me change it in the future easily.

Here is the table when the CLI is running and waiting for its children to be terminated. Those circle icons indicates that *Hey user, I am doing your task ..* 

![screenshot watch](https://user-images.githubusercontent.com/18571844/60164441-d1e83480-9812-11e9-8e75-6214000d6e80.png)

and here is when the tasks have been done

![screenshot](https://user-images.githubusercontent.com/18571844/60164490-eaf0e580-9812-11e9-91d2-67df55fbcc0d.png)

### NOTE
Although in my opinion it is *cool*, *clean*, *etc* I added an option for the CLI so the user can **choose** **not** to use the table! A problem that right now webpack has and a user is not able to **ignore** `config` file via `--config` option.

I will be glad to help you to have a simple, yet good Command Line Interface.

**Comment by Kolhar730** [comment]
@evenstensberg is this issue still open? Anyway, I could contribute here?

**Comment by evenstensberg** [comment]
Yes it's still open but this is mostly a discussion thread for us to get feedback from.

**Comment by evenstensberg** [comment]
I think maybe that it is worth adding another row to the output table that will show the entries mapped against their output bundles, will make it easier to check the entry-output relationship
